services:
    suivi_main.menu_builder:
        class: Suivi\MainBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]

    suivi_main.menu.top:
        class: Knp\Menu\MenuItem
        factory_service: suivi_main.menu_builder
        factory_method: createTopMenu
        tags:
            - { name: knp_menu.menu, alias: main_top }