# Routing for fos user bundle
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

SuiviMainBundle:
    resource: "@SuiviMainBundle/Controller/"
    type:     annotation

SuiviAdminBundle:
    resource: "@SuiviAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin